# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/win-64/asn1crypto-0.22.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/certifi-2016.2.28-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cffi-1.10.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/colorama-0.3.7-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cryptography-1.8.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/decorator-4.0.10-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/idna-2.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ipython-5.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ipython_genutils-0.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/openssl-1.0.2l-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/packaging-16.8-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/path.py-8.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pickleshare-0.7.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pip-8.1.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/prompt_toolkit-1.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pycparser-2.17-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pygments-2.1.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyopenssl-17.0.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyparsing-2.1.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pysocks-1.6.6-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/python-3.5.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/requests-2.11.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/setuptools-26.1.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/simplegeneric-0.8.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/six-1.10.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/traitlets-4.2.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/urllib3-1.21.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/vs2015_runtime-14.0.25123-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/wcwidth-0.1.7-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/wheel-0.29.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/win_inet_pton-1.0.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/win_unicode_console-0.5-py35_0.tar.bz2
